### ISSUE TITLE
Support for async await syntax?

### ISSUE THREAD

**Issue by rudrankriyam** [glassfy/ios-sdk#1]
Hi! 

I came across this iOS SDK, and curious if the methods support async await syntax for iOS 13+. Thanks!

**Comment by SAllen0400** [comment]
Any plans to implement async/await versions of methods?

**Comment by fcurzel** [comment]
Hello @rudrankriyam and @SAllen0400, sorry for the late response.
Async/Await compatibility methods are automatically generated and have been present in the SDK for a while, unfortunately, our documentation did not mention it.

You can find more information on how this is possible [here](https://developer.apple.com/documentation/swift/calling-objective-c-apis-asynchronously).

In short, if an Objective C method has a closure parameter, it automatically offers two Swift counterparts (one async/await and one with the classic closure).

This is how the methods should show up in your Xcode autocomplete:
![image](https://github.com/glassfy/ios-sdk/assets/128367484/998fa428-da57-42b5-a9f3-fe7ca2733114)

For example, both of these are valid:
```swift
// Async/Await
do {
    let permissions = try await Glassfy.restorePurchases()
    // Use permissions.all
} catch {
    // Error handling
}

// Classic completion block
Glassfy.restorePurchases { permissions, error in
    // ...
}
```

With that said, I will update the documentation soon!
